name: Compile and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/compile-and-deploy.yml"
      - "GithubActionsDemoApp/**"
      - "Tests/**"
    tags:
      - '*'
  

env:
  DOTNET_VERSION: 8.0.x
  PROJECT: GithubActionsDemoApp/GithubActionsDemoApp.csproj

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Getting the dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build

      - name: Publish
        run: dotnet publish ${{env.PROJECT}} -c Release -o myapp --runtime win-x86

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: ./myapp
          name: build

      - name: Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -r myapp.zip ./myapp

      - name: GH Release
        uses: softprops/action-gh-release@v2.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./myapp.zip
          body: "Our application"
          tag_name: ${{ github.ref_name }}
